FROM nvidia/cuda:12.1.0-devel-ubuntu18.04

ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

# SHELL ["/bin/bash", "-c"]

RUN apt-get update && DEBIAN_FRONTEND=noninteractive TZ=Asia/Yekaterinburg \apt-get -y install python3-opencv --no-install-recommends \
    python3-pip \
    python3-setuptools

RUN pip3 install --upgrade pip

RUN pip3 install opencv-python==4.8.0.74

COPY requirements.txt /tmp/requirements.txt
RUN pip3 --no-cache-dir install -r /tmp/requirements.txt
# RUN pip install onnxruntime onnx argparse

WORKDIR /mnt/
COPY . /app/

CMD ["/bin/bash", "-c", "python3 -u /app/main.py"]

