FROM nvidia/cuda:12.1.0-devel-ubuntu18.04
RUN apt-get update && DEBIAN_FRONTEND=noninteractive TZ=Asia/Yekaterinburg \apt-get -y install python3-opencv --no-install-recommends
WORKDIR /mnt/
COPY . /app/
CMD ["/usr/bin/python3", "/app/main.py"]
